### ISSUE TITLE
Nonintuitive maximum limit for ANIm for a given organism

### ISSUE THREAD

**Issue by mhibberd** [widdowquinn/pyani#91]
#### Summary:
Attempts to understand the process of ANIm calculation (using comparisons of a given genome to itself) led to ANIm values < 1.0 and coverage values > 1.0.

#### Description:
I noticed a number of strangely limited values when comparing sets of highly-similar genomes to each other using pyani and the ANIm approach. As a test I added in a copied version of one of my genomes with a different filename, comparison of which yielded non-intuitive results of ANIm < 1.0 and coverage > 1.0.

#### Reproducible Steps:
Genome sequence downloaded from NCBI:
[https://www.ncbi.nlm.nih.gov/nuccore/CP001095]([https://www.ncbi.nlm.nih.gov/nuccore/CP001095])

Copied version generated:
cp NC_CP001095.fasta NC_CP001095_v2.fasta

ANIm calculated:
average_nucleotide_identity.py -i ./ -o ANI_comp/

#### Current Output:
ANIm: 0.998
Alignment Coverage: 1.027

#### Expected Output:
Would have expected 1.0 for both.

#### pyani Version:
v0.2.3
#### Python Version:
3.6.2
#### Operating System:
MacOS Sierra 10.12.6

**Comment by widdowquinn** [comment]
Thanks for the report, Matt.

You're correct, the result is not what we should expect, and the issue is due to how `pyani` currently calls `NUCmer`. I will shortly implement a fix in the current release, bump the version number and put out a new release via `pypi`. 

### What's going wrong

In the current version (0.2.3) the call to `NUCmer` is able to generate more than one alignment for a given section of the genome, even though the MUMs themselves are constrained to be unique with the `-mum` argument. This is probably what is responsible for your observed result:

- NUCmer aligns both versions of the genome exactly; but it also identifies one or more similar repeated regions that are not exact matches, and aligns the repeats separately.
- Both alignments of the repeated region are reported in the .delta file, and are subsequently used when calculating ANI. This is not the expected behaviour.

The error is, unfortunately, masked in the `seaborn` graphical output, as it only reports to 2 decimal places, but is evident when using the `.tab` output.

### How to fix it

A fix for this (which will be implemented in v0.3) is to use `MUMmer`'s `delta-filter` with the `-1` argument to retain only one match per region. You can do this manually if you like, or you can use the [untested ‘classify’ branch](https://github.com/widdowquinn/pyani/tree/classify) of the source code. Note, though, that the UI has changed somewhat with the move from v0.2 to what will become v0.3!

An example `delta-filter` command line would be:

`delta-filter -1 <comparison>.delta > <comparison>.filter`

With your test genome, the number of reported alignments between the two identical genomes is 82 when `delta-filter` is not used, and 1 when `delta-filter` is used.

[GCA_000020425.1_ASM2042v1_genomic_vs_genome_copy.delta.txt](https://github.com/widdowquinn/pyani/files/1214121/GCA_000020425.1_ASM2042v1_genomic_vs_genome_copy.delta.txt)
[GCA_000020425.1_ASM2042v1_genomic_vs_genome_copy.filter.txt](https://github.com/widdowquinn/pyani/files/1214122/GCA_000020425.1_ASM2042v1_genomic_vs_genome_copy.filter.txt)

### A related, but non-error issue

You may occasionally still see coverage values greater than 1, and this is potentially valid output.

If two different genomes are sufficiently similar to align over their complete lengths, but the alignment requires indels, then the length of the alignment may be greater than the shorter and/or longer genome. Coverage is reported as alignment length/genome length, so this results in a coverage greater than 1.

I am in two minds as to whether this requires a 'cap' on coverage reporting, so for values greater than 1 we report as exactly 1 instead. For now, I'm leaving this behaviour alone.

**Comment by widdowquinn** [comment]
That should be the issue fixed with v0.2.4:

* [GitHub release](https://github.com/widdowquinn/pyani/releases/tag/v0.2.4)
* [PyPI](https://pypi.python.org/pypi/pyani/0.2.4)

Please give it a go and, if all seems well, I'll close the issue.

**Comment by mhibberd** [comment]
Hi Leighton,
I've pulled the changes from github and re-ran the software as before, but I'm still getting the absolute same values out for ANIm with the same genome. I'm sorry to obsess over comparing self-self but I want to make sure I understand the upper limit here.
Thanks!

**Comment by widdowquinn** [comment]
No worries, Matt - my apologies for the inconvenience. I got different results using your example genome, so let's go through some things to check we're keeping pace all the way through (you'll probably have done this, anyway…)

1. Are we sure you're running the right version of `pyani`?

```
$ average_nucleotide_identity.py --version
average_nucleotide_identity.py: pyani 0.2.4
```

There was an issue with the version number bump not being in `master` that I hadn't noticed. This should be fixed with a new `git pull` (if you cloned the repo), then `python setup.py install`. Alternatively, issuing `pip install pyani -U` worked for me, as well.

2. Get the test data

I put the `CP001095` genome in the subdirectory `issue_91`, and copied it to the file `genome_copy.fna`. You've probably got a similar setup already:

```
$ ls issue_91/
GCA_000020425.1_ASM2042v1_genomic.fna  genome_copy.fna
$ head -n 2 issue_91/*
==> issue_91/GCA_000020425.1_ASM2042v1_genomic.fna <==
>CP001095.1 Bifidobacterium longum subsp. infantis ATCC 15697, complete genome
TTTCACATTTCGACACGTTGCGAGACACGCCTCAGATCTCTTATAATCGGCGGAATACCAACCATTCACGGCCAAAAGTT

==> issue_91/genome_copy.fna <==
>CP001095.1 Bifidobacterium longum subsp. infantis ATCC 15697, complete genome
TTTCACATTTCGACACGTTGCGAGACACGCCTCAGATCTCTTATAATCGGCGGAATACCAACCATTCACGGCCAAAAGTT
```

3. Run `pyani`

```
$ average_nucleotide_identity.py -v -i issue_91/ -o issue_91_new -m ANIm -g --gformat png,pdf, --gmethod seaborn -l 2017-08-10_test.log
INFO: pyani version: 0.2.4
[...]
INFO: Done: Thu Aug 10 18:04:56 2017.
INFO: Time taken: 18.30s
```

and check the results

```
$ cat issue_91_new/ANIm_percentage_identity.tab
	GCA_000020425.1_ASM2042v1_genomic	genome_copy
GCA_000020425.1_ASM2042v1_genomic	1.0	1.0
genome_copy	1.0	1.0
```

If the rest of your actions give the same output as mine, then there's something a bit awry - perhaps some namespace confusion caused by running the script from within the repository.

**Comment by mhibberd** [comment]
Leighton,
Fixed. I did notice previously when I'd checked the version of average_nucleotide_identity.py it was giving me something like 0.2.3-dev. The correct version is now reported and the script behaving as advertised.
Thanks!

**Comment by widdowquinn** [comment]
Brilliant! Thank you for the report, and for your patience!
